# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: flutter-web-deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.12.0

      - name: Analyze code
        run: flutter analyze

      - name: Build for web
        run: flutter build web

      - name: Upload build results
        uses: actions/upload-pages-artifact@v2.0.0
        with:
          path: 'build/web/.'

      - name: Deploy to pages
        id: deployment
        uses: actions/deploy-pages@v3.0.1
        
